# Generated by Django 4.1.1 on 2022-10-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('account_no', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('s_acholdername', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('s_pic', models.ImageField(upload_to='reseller/')),
            ],
        ),
    ]
