# Generated by Django 4.1.2 on 2022-10-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_number', models.BigIntegerField()),
                ('p_details', models.CharField(max_length=300)),
                ('p_price', models.BigIntegerField()),
                ('p_stock', models.BigIntegerField()),
                ('p_image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reseller_app.reseller')),
            ],
        ),
    ]
