# Generated by Django 4.1.2 on 2022-11-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller_app', '0004_rename_seller_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='s_status',
            field=models.IntegerField(default=1),
        ),
    ]
